# Generated by Django 2.2.1 on 2019-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20191025_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comedians',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
