# Generated by Django 2.2.1 on 2019-10-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comedians', '0008_auto_20191029_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('age_limit', models.CharField(blank=True, max_length=10)),
                ('date_time', models.DateTimeField()),
                ('comedians', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedians.RegisterComedian')),
            ],
        ),
    ]
