# Generated by Django 2.2.1 on 2019-10-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomedian',
            name='insta_link',
            field=models.URLField(blank=True),
        ),
    ]
