# Generated by Django 2.2.1 on 2019-10-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0002_registercomedian_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomedian',
            name='email',
            field=models.TextField(default='email@company.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registercomedian',
            name='phoneno',
            field=models.TextField(default=9876543210, max_length=13),
            preserve_default=False,
        ),
    ]
