# Generated by Django 2.2.1 on 2019-10-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0003_auto_20191026_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registercomedian',
            name='phoneno',
            field=models.CharField(max_length=13),
        ),
    ]
