# Generated by Django 2.2.1 on 2019-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0004_auto_20191026_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomedian',
            name='test_multi_field',
            field=models.TextField(default='https://www.youtube.com/channel/UCNf9HsbAQXqV5Oozl1Vs4pA?view_as=subscriber', max_length=100),
            preserve_default=False,
        ),
    ]
