# Generated by Django 2.2.1 on 2019-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0007_auto_20191027_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomedian',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pp.jpg', upload_to='profile_pic/'),
        ),
    ]
